/**
 * Comprehensive POS Error Scenarios
 * Based on real-world Point of Sale system challenges
 */

export interface POSErrorScenario {
    id: string;
    category: 'payment' | 'inventory' | 'network' | 'hardware' | 'database' | 'integration' | 'security' | 'performance' | 'data' | 'system';
    name: string;
    description: string;
    severity: 'critical' | 'high' | 'medium' | 'low';
    errorCode: string;
    message: string;
    symptoms: string[];
    causes: string[];
    businessImpact: string;
    immediateActions: string[];
    longTermFix: string;
    affectedComponents: string[];
    probability: number; // 0-100, higher = more likely to occur
}

export const POS_ERROR_SCENARIOS: POSErrorScenario[] = [
    // PAYMENT PROCESSING ERRORS (Most Critical)
    {
        id: 'PAY_001',
        category: 'payment',
        name: 'Payment Gateway Timeout',
        description: 'Payment processor not responding within timeout period',
        severity: 'critical',
        errorCode: 'PAYMENT_TIMEOUT',
        message: 'Payment gateway timeout - transaction took longer than 30 seconds',
        symptoms: ['Customer waiting', 'Transaction pending', 'Terminal frozen'],
        causes: ['Network latency', 'Gateway server overload', 'Network congestion', 'DDoS attack'],
        businessImpact: 'Customer cannot complete purchase, lost sale, poor customer experience',
        immediateActions: ['Retry transaction', 'Switch to backup payment processor', 'Offer alternative payment method'],
        longTermFix: 'Implement circuit breaker pattern, add backup payment gateway, optimize timeout values',
        affectedComponents: ['Payment Terminal', 'Network', 'Payment Gateway API'],
        probability: 15
    },
    {
        id: 'PAY_002',
        category: 'payment',
        name: 'Card Declined - Insufficient Funds',
        description: 'Customer card has insufficient funds for transaction',
        severity: 'medium',
        errorCode: 'CARD_DECLINED_NSF',
        message: 'Card declined: Insufficient funds in account',
        symptoms: ['Payment rejected', 'Customer embarrassment', 'Need alternative payment'],
        causes: ['Low account balance', 'Card limit reached', 'Pending authorizations'],
        businessImpact: 'Sale delayed, customer may abandon cart, staff time consumed',
        immediateActions: ['Inform customer politely', 'Offer alternative payment method', 'Suggest removing items'],
        longTermFix: 'Implement pre-authorization checks, offer payment plans, integrate multiple payment options',
        affectedComponents: ['Payment Terminal', 'Card Reader'],
        probability: 25
    },
    {
        id: 'PAY_003',
        category: 'payment',
        name: 'EMV Chip Read Failure',
        description: 'Failed to read chip on EMV credit/debit card',
        severity: 'high',
        errorCode: 'EMV_READ_ERROR',
        message: 'Unable to read chip card - chip may be damaged or dirty',
        symptoms: ['Multiple read attempts', 'Please insert card message', 'Fallback to swipe'],
        causes: ['Damaged chip', 'Dirty chip contacts', 'Faulty card reader', 'Worn reader contacts'],
        businessImpact: 'Transaction delay, potential fraud risk from fallback, customer frustration',
        immediateActions: ['Try cleaning chip', 'Attempt swipe fallback', 'Use different terminal', 'Enter card manually'],
        longTermFix: 'Regular terminal maintenance, reader contact cleaning schedule, replace aging terminals',
        affectedComponents: ['EMV Chip Reader', 'Payment Terminal'],
        probability: 20
    },
    {
        id: 'PAY_004',
        category: 'payment',
        name: 'Split Payment Failure',
        description: 'Error processing transaction split across multiple payment methods',
        severity: 'medium',
        errorCode: 'SPLIT_PAYMENT_ERROR',
        message: 'Failed to process split payment - partial authorization issue',
        symptoms: ['First payment successful, second fails', 'Inconsistent transaction state', 'Refund needed'],
        causes: ['Payment processor limitation', 'Insufficient balance on second method', 'System state inconsistency'],
        businessImpact: 'Complex refund process, customer dissatisfaction, transaction reconciliation issues',
        immediateActions: ['Void first transaction', 'Restart payment process', 'Use single payment method'],
        longTermFix: 'Implement atomic split payment transactions, improve error recovery, add rollback mechanism',
        affectedComponents: ['Payment Processing', 'Transaction Manager'],
        probability: 12
    },
    {
        id: 'PAY_005',
        category: 'payment',
        name: 'Duplicate Transaction Posted',
        description: 'Same transaction processed multiple times due to network retry',
        severity: 'critical',
        errorCode: 'DUPLICATE_CHARGE',
        message: 'Duplicate transaction detected - customer charged twice',
        symptoms: ['Multiple authorizations', 'Customer complaint', 'Reconciliation mismatch'],
        causes: ['Network timeout with retry', 'Double-tap by customer', 'System bug', 'Idempotency key missing'],
        businessImpact: 'Customer overcharged, dispute/chargeback risk, trust damage, refund processing cost',
        immediateActions: ['Immediately void duplicate', 'Issue refund', 'Document incident', 'Notify customer'],
        longTermFix: 'Implement idempotency keys, transaction deduplication, proper retry logic with exponential backoff',
        affectedComponents: ['Payment Gateway', 'Transaction Manager', 'Network Layer'],
        probability: 8
    },

    // INVENTORY MANAGEMENT ERRORS
    {
        id: 'INV_001',
        category: 'inventory',
        name: 'Out of Stock - System Mismatch',
        description: 'Item shows available in system but physically out of stock',
        severity: 'high',
        errorCode: 'INVENTORY_MISMATCH',
        message: 'Inventory count mismatch - item not available despite system showing stock',
        symptoms: ['Cannot fulfill order', 'Customer disappointment', 'Need stock check'],
        causes: ['Unrecorded shrinkage', 'Theft', 'Receiving error', 'Failed sync', 'Manual count error'],
        businessImpact: 'Lost sale, customer dissatisfaction, inventory accuracy issues, potential regulatory violation',
        immediateActions: ['Check backroom/storage', 'Offer substitute', 'Physical recount', 'Update system'],
        longTermFix: 'Implement real-time inventory tracking, RFID tags, cycle counting, automated reconciliation',
        affectedComponents: ['Inventory Management', 'Database', 'Barcode Scanner'],
        probability: 18
    },
    {
        id: 'INV_002',
        category: 'inventory',
        name: 'Barcode Scan Failure',
        description: 'Unable to scan product barcode - damaged or missing',
        severity: 'medium',
        errorCode: 'BARCODE_NOT_FOUND',
        message: 'Barcode not recognized - no product match in database',
        symptoms: ['Repeated scan attempts', 'Manual entry needed', 'Transaction delay'],
        causes: ['Damaged label', 'Missing barcode', 'Incorrect barcode', 'Scanner malfunction', 'Database missing SKU'],
        businessImpact: 'Slow checkout, customer wait time, potential pricing errors, staff frustration',
        immediateActions: ['Manual SKU entry', 'Try different scanner', 'Check product database', 'Use SKU lookup'],
        longTermFix: 'QA on barcode quality, backup identification methods (images, NFC), regular database audits',
        affectedComponents: ['Barcode Scanner', 'Product Database', 'POS Terminal'],
        probability: 22
    },
    {
        id: 'INV_003',
        category: 'inventory',
        name: 'Negative Stock Error',
        description: 'System attempting to set inventory to negative value',
        severity: 'medium',
        errorCode: 'NEGATIVE_STOCK',
        message: 'Cannot process sale - would result in negative inventory count',
        symptoms: ['Transaction blocked', 'Inventory count warning', 'Need manager override'],
        causes: ['Concurrent transactions', 'Race condition', 'Sync delay', 'Initial count wrong'],
        businessImpact: 'Sale blocked, potential inventory accuracy issues, system integrity concern',
        immediateActions: ['Verify physical stock', 'Manager override if stock available', 'Check other locations'],
        longTermFix: 'Implement optimistic locking, inventory reservation system, proper transaction isolation',
        affectedComponents: ['Inventory Database', 'Transaction Manager'],
        probability: 10
    },
    {
        id: 'INV_004',
        category: 'inventory',
        name: 'Price Lookup Failure',
        description: 'Product has no price in system or price lookup fails',
        severity: 'high',
        errorCode: 'PRICE_NOT_FOUND',
        message: 'No price found for product - unable to complete sale',
        symptoms: ['Transaction halted', 'Manager call needed', 'Customer waiting'],
        causes: ['Missing price entry', 'Price update failed', 'Database corruption', 'New product not configured'],
        businessImpact: 'Transaction cannot complete, customer abandonment risk, revenue loss, staff time wasted',
        immediateActions: ['Check shelf price', 'Manager price override', 'Look up in central system'],
        longTermFix: 'Mandatory price validation on product creation, automated price sync, fallback pricing logic',
        affectedComponents: ['Product Database', 'Pricing Engine'],
        probability: 14
    },

    // NETWORK & CONNECTIVITY ERRORS
    {
        id: 'NET_001',
        category: 'network',
        name: 'Database Connection Lost',
        description: 'Connection to central database server dropped',
        severity: 'critical',
        errorCode: 'DB_CONNECTION_LOST',
        message: 'Lost connection to database server - cannot process transactions',
        symptoms: ['All terminals affected', 'Cannot lookup products', 'Cannot process sales'],
        causes: ['Network outage', 'Database server down', 'Firewall blocking', 'Network switch failure'],
        businessImpact: 'Complete POS shutdown, all sales stopped, customer exodus, major revenue loss',
        immediateActions: ['Check network connection', 'Restart network equipment', 'Switch to offline mode', 'Manual receipts'],
        longTermFix: 'Implement offline mode with local cache, redundant network paths, database failover, regular network monitoring',
        affectedComponents: ['Network', 'Database Server', 'All POS Terminals'],
        probability: 8
    },
    {
        id: 'NET_002',
        category: 'network',
        name: 'API Rate Limit Exceeded',
        description: 'Third-party API rate limit reached during high traffic',
        severity: 'high',
        errorCode: 'RATE_LIMIT_EXCEEDED',
        message: 'API rate limit exceeded - too many requests in short period',
        symptoms: ['Intermittent failures', 'Slow response', 'Some transactions fail'],
        causes: ['High transaction volume', 'Missing rate limit handling', 'Concurrent requests', 'No request queuing'],
        businessImpact: 'Reduced transaction throughput, customer wait time increased, potential lost sales',
        immediateActions: ['Implement exponential backoff', 'Queue requests', 'Use alternative API endpoint'],
        longTermFix: 'Implement request rate limiting, caching layer, API request queuing, negotiate higher limits',
        affectedComponents: ['API Client', 'Integration Layer'],
        probability: 12
    },
    {
        id: 'NET_003',
        category: 'network',
        name: 'Cloud Service Degradation',
        description: 'Cloud-hosted POS services experiencing performance issues',
        severity: 'high',
        errorCode: 'CLOUD_DEGRADED',
        message: 'Cloud services responding slowly - system degraded',
        symptoms: ['Slow response times', 'Timeout errors', 'Intermittent failures'],
        causes: ['Cloud provider outage', 'DDoS attack', 'Resource exhaustion', 'Regional failure'],
        businessImpact: 'Slow checkout process, customer frustration, reduced transaction capacity',
        immediateActions: ['Monitor cloud status page', 'Switch to backup region', 'Enable offline mode'],
        longTermFix: 'Multi-region deployment, auto-scaling, CDN for static assets, hybrid cloud/local architecture',
        affectedComponents: ['Cloud Infrastructure', 'API Services'],
        probability: 10
    },

    // HARDWARE FAILURES
    {
        id: 'HW_001',
        category: 'hardware',
        name: 'Receipt Printer Paper Jam',
        description: 'Receipt printer jammed or out of paper',
        severity: 'medium',
        errorCode: 'PRINTER_JAM',
        message: 'Receipt printer error - paper jam or out of paper',
        symptoms: ['No receipt printed', 'Printer error light', 'Customer needs receipt'],
        causes: ['Paper jam', 'Empty paper roll', 'Worn printer mechanism', 'Dust buildup'],
        businessImpact: 'Cannot provide receipt, customer dissatisfaction, potential return issues, warranty problems',
        immediateActions: ['Clear jam', 'Replace paper', 'Email receipt option', 'Use backup printer'],
        longTermFix: 'Regular printer maintenance, receipt buffer to retry, auto paper level alerts, digital receipt default',
        affectedComponents: ['Receipt Printer', 'Printer Driver'],
        probability: 28
    },
    {
        id: 'HW_002',
        category: 'hardware',
        name: "Cash Drawer Won't Open",
        description: 'Electronic cash drawer failed to open',
        severity: 'high',
        errorCode: 'CASH_DRAWER_ERROR',
        message: 'Cash drawer failed to open - mechanism stuck',
        symptoms: ['Drawer locked', 'Cannot access cash', 'Manual key needed'],
        causes: ['Electronic mechanism failure', 'Power issue', 'Jammed bills', 'Loose cable'],
        businessImpact: 'Cannot accept cash payments, cannot give change, limited payment options, customer inconvenience',
        immediateActions: ['Check power/cables', 'Use manual key', 'Move to another terminal', 'Card-only transactions'],
        longTermFix: 'Regular maintenance, backup manual operation, monitor drawer sensor status',
        affectedComponents: ['Cash Drawer', 'Terminal Interface'],
        probability: 15
    },
    {
        id: 'HW_003',
        category: 'hardware',
        name: 'Touchscreen Calibration Drift',
        description: 'POS touchscreen not responding accurately to touch',
        severity: 'medium',
        errorCode: 'TOUCHSCREEN_DRIFT',
        message: 'Touchscreen calibration error - touches registering in wrong location',
        symptoms: ['Wrong buttons pressed', 'Need multiple taps', 'Staff frustration'],
        causes: ['Screen wear', 'Calibration drift', 'Screen protector issue', 'Hardware degradation'],
        businessImpact: 'Slow transactions, entry errors, staff productivity loss, potential transaction mistakes',
        immediateActions: ['Recalibrate screen', 'Clean screen', 'Use keyboard/mouse', 'Switch terminals'],
        longTermFix: 'Regular calibration schedule, quality screen protectors, terminal replacement schedule',
        affectedComponents: ['Touchscreen', 'POS Terminal'],
        probability: 16
    },
    {
        id: 'HW_004',
        category: 'hardware',
        name: 'Barcode Scanner Malfunction',
        description: 'Barcode scanner not reading or scanning intermittently',
        severity: 'high',
        errorCode: 'SCANNER_ERROR',
        message: 'Barcode scanner malfunction - inconsistent reads',
        symptoms: ['Multiple scan attempts needed', 'No scan beep', 'Slow checkout'],
        causes: ['Dirty scanner window', 'Damaged laser', 'Cable loose', 'Low battery (wireless)'],
        businessImpact: 'Very slow checkout, long queues, customer abandonment, staff frustration',
        immediateActions: ['Clean scanner', 'Check cable/battery', 'Manual entry', 'Use backup scanner'],
        longTermFix: 'Regular cleaning schedule, scanner battery monitoring, backup scanners, replacement plan',
        affectedComponents: ['Barcode Scanner', 'USB/Wireless Connection'],
        probability: 24
    },

    // DATABASE & DATA INTEGRITY ERRORS
    {
        id: 'DB_001',
        category: 'database',
        name: 'Transaction Deadlock',
        description: 'Database deadlock detected during concurrent transactions',
        severity: 'high',
        errorCode: 'DB_DEADLOCK',
        message: 'Database deadlock detected - transaction rolled back',
        symptoms: ['Transaction fails', 'Retry needed', 'Performance degradation'],
        causes: ['Concurrent updates', 'Lock contention', 'Poor indexing', 'Complex transactions'],
        businessImpact: 'Transaction failures, customer retry needed, system performance impact',
        immediateActions: ['Retry transaction', 'Reduce transaction scope', 'Check for long-running queries'],
        longTermFix: 'Optimize queries, add proper indexes, implement optimistic locking, reduce transaction scope',
        affectedComponents: ['Database', 'Transaction Manager'],
        probability: 10
    },
    {
        id: 'DB_002',
        category: 'database',
        name: 'Data Corruption Detected',
        description: 'Database integrity check failed - corrupted data found',
        severity: 'critical',
        errorCode: 'DATA_CORRUPTION',
        message: 'Data corruption detected - database integrity compromised',
        symptoms: ['Inconsistent data', 'Query errors', 'Missing records'],
        causes: ['Hardware failure', 'Power outage during write', 'Software bug', 'Disk failure'],
        businessImpact: 'Potential data loss, system unreliability, audit compliance issues, financial discrepancies',
        immediateActions: ['Stop writes', 'Restore from backup', 'Run integrity check', 'Isolate affected data'],
        longTermFix: 'Regular backups, RAID storage, UPS power protection, database replication',
        affectedComponents: ['Database', 'Storage System'],
        probability: 3
    },
    {
        id: 'DB_003',
        category: 'database',
        name: 'Connection Pool Exhaustion',
        description: 'All database connections in pool are in use',
        severity: 'high',
        errorCode: 'CONN_POOL_EXHAUSTED',
        message: 'Database connection pool exhausted - no available connections',
        symptoms: ['New requests timeout', 'System slows down', 'Error spike'],
        causes: ['Connection leaks', 'High traffic', 'Slow queries', 'Insufficient pool size'],
        businessImpact: 'System can\'t accept new transactions, customer wait time, potential downtime',
        immediateActions: ['Restart application', 'Kill long-running queries', 'Increase pool size temporarily'],
        longTermFix: 'Fix connection leaks, optimize queries, implement connection timeout, scale pool size',
        affectedComponents: ['Database Connection Pool', 'Application Server'],
        probability: 12
    },

    // INTEGRATION & THIRD-PARTY ERRORS
    {
        id: 'INT_001',
        category: 'integration',
        name: 'Loyalty System API Down',
        description: 'Customer loyalty points system unavailable',
        severity: 'medium',
        errorCode: 'LOYALTY_API_DOWN',
        message: 'Loyalty system unavailable - cannot apply points or rewards',
        symptoms: ['Points not applied', 'Rewards unavailable', 'Customer complaints'],
        causes: ['API downtime', 'Network issue', 'Authentication failure', 'Service maintenance'],
        businessImpact: 'Cannot honor rewards, customer dissatisfaction, competitive disadvantage, loyalty program disruption',
        immediateActions: ['Manual points entry later', 'Provide discount equivalent', 'Document for later update'],
        longTermFix: 'Implement offline loyalty mode, cache recent customer data, fallback discount rules',
        affectedComponents: ['Loyalty API', 'Integration Layer'],
        probability: 14
    },
    {
        id: 'INT_002',
        category: 'integration',
        name: 'Tax Calculation Service Error',
        description: 'Real-time tax calculation service failed',
        severity: 'high',
        errorCode: 'TAX_CALC_ERROR',
        message: 'Tax calculation service error - cannot determine correct tax amount',
        symptoms: ['Transaction blocked', 'Tax missing', 'Need manual calculation'],
        causes: ['API failure', 'Address validation failed', 'Service timeout', 'Invalid product tax category'],
        businessImpact: 'Cannot complete sale, potential tax compliance issues, revenue recognition problems',
        immediateActions: ['Use default tax rate', 'Manager override', 'Manual calculation'],
        longTermFix: 'Cache tax rates locally, fallback tax calculation, regular rate updates',
        affectedComponents: ['Tax Service API', 'Pricing Engine'],
        probability: 8
    },
    {
        id: 'INT_003',
        category: 'integration',
        name: 'Email Receipt Service Down',
        description: 'Email receipt delivery system not responding',
        severity: 'low',
        errorCode: 'EMAIL_SERVICE_DOWN',
        message: 'Cannot send email receipt - service unavailable',
        symptoms: ['Email not sent', 'Customer not receiving receipt', 'Queue building'],
        causes: ['SMTP server down', 'Network issue', 'Rate limit', 'Authentication failure'],
        businessImpact: 'No digital receipt, customer inconvenience, paper waste, potential dispute issues',
        immediateActions: ['Print paper receipt', 'Queue for later', 'Try SMS option'],
        longTermFix: 'Implement email queue with retry, backup email service, SMS fallback',
        affectedComponents: ['Email Service', 'SMTP Server'],
        probability: 18
    },

    // SECURITY & AUTHENTICATION ERRORS
    {
        id: 'SEC_001',
        category: 'security',
        name: 'Employee Authentication Failure',
        description: 'Cashier unable to authenticate to POS system',
        severity: 'high',
        errorCode: 'AUTH_FAILED',
        message: 'Authentication failed - invalid credentials or account locked',
        symptoms: ['Cannot login', 'Shift cannot start', 'Terminal unusable'],
        causes: ['Wrong password', 'Account locked', 'LDAP down', 'Password expired', 'Network issue'],
        businessImpact: 'Terminal unavailable, reduced capacity, line buildup, customer wait time',
        immediateActions: ['Reset password', 'Unlock account', 'Use backup account', 'Manual authentication'],
        longTermFix: 'Self-service password reset, biometric authentication, offline authentication cache',
        affectedComponents: ['Authentication Service', 'User Database'],
        probability: 16
    },
    {
        id: 'SEC_002',
        category: 'security',
        name: 'PCI Compliance Violation Detected',
        description: 'System detected PCI DSS compliance violation',
        severity: 'critical',
        errorCode: 'PCI_VIOLATION',
        message: 'PCI compliance violation detected - unencrypted card data found',
        symptoms: ['Compliance alert', 'Audit flag', 'System lockdown'],
        causes: ['Unencrypted data storage', 'Logging card numbers', 'Improper data handling'],
        businessImpact: 'Legal liability, fines up to $500k, loss of payment processing ability, reputation damage',
        immediateActions: ['Stop system', 'Secure data', 'Notify compliance team', 'Investigation'],
        longTermFix: 'End-to-end encryption, tokenization, PCI audit, staff training, security monitoring',
        affectedComponents: ['Payment System', 'Data Storage', 'Logging System'],
        probability: 2
    },
    {
        id: 'SEC_003',
        category: 'security',
        name: 'Suspicious Transaction Pattern',
        description: 'Fraud detection system flagged unusual transaction',
        severity: 'high',
        errorCode: 'FRAUD_ALERT',
        message: 'Suspicious transaction detected - potential fraud',
        symptoms: ['Transaction flagged', 'Manager approval needed', 'Customer verification required'],
        causes: ['Unusual pattern', 'High value', 'Multiple cards', 'Velocity check failed'],
        businessImpact: 'Transaction delayed, customer inconvenience, potential fraud loss if ignored',
        immediateActions: ['Verify customer ID', 'Manager approval', 'Contact card issuer', 'Additional verification'],
        longTermFix: 'Improve fraud detection rules, machine learning model, real-time verification APIs',
        affectedComponents: ['Fraud Detection', 'Transaction Monitor'],
        probability: 10
    },

    // PERFORMANCE & SYSTEM ERRORS
    {
        id: 'PERF_001',
        category: 'performance',
        name: 'Memory Leak Detected',
        description: 'POS application consuming excessive memory',
        severity: 'high',
        errorCode: 'MEMORY_LEAK',
        message: 'High memory usage detected - potential memory leak',
        symptoms: ['System slowdown', 'Application crashes', 'Need frequent restarts'],
        causes: ['Software bug', 'Resource not released', 'Cache overflow', 'Connection leaks'],
        businessImpact: 'System instability, frequent crashes, reduced uptime, lost transactions',
        immediateActions: ['Restart application', 'Monitor memory usage', 'Reduce load'],
        longTermFix: 'Fix memory leaks, implement memory monitoring, auto-restart on threshold, code review',
        affectedComponents: ['Application Server', 'Runtime Environment'],
        probability: 8
    },
    {
        id: 'PERF_002',
        category: 'performance',
        name: 'Disk Space Critical',
        description: 'POS terminal running out of disk space',
        severity: 'high',
        errorCode: 'DISK_FULL',
        message: 'Critical: Disk space below 5% - system may fail',
        symptoms: ['Cannot save data', 'Log errors', 'System slowdown'],
        causes: ['Log file growth', 'Cache buildup', 'Failed cleanup', 'Large database'],
        businessImpact: 'System failure risk, data loss potential, cannot process new transactions',
        immediateActions: ['Delete old logs', 'Clear temp files', 'Archive data', 'Free up space'],
        longTermFix: 'Automated log rotation, cloud storage, regular cleanup jobs, monitoring alerts',
        affectedComponents: ['Local Storage', 'File System'],
        probability: 12
    },
    {
        id: 'PERF_003',
        category: 'performance',
        name: 'CPU Overload',
        description: 'POS system CPU usage exceeding 90%',
        severity: 'high',
        errorCode: 'CPU_OVERLOAD',
        message: 'CPU usage critical - system performance degraded',
        symptoms: ['Slow response', 'UI freezes', 'Transactions timeout'],
        causes: ['Heavy processing', 'Inefficient code', 'Too many concurrent operations', 'Resource contention'],
        businessImpact: 'Severely slow checkout, customer frustration, reduced transaction throughput',
        immediateActions: ['Kill non-essential processes', 'Restart system', 'Reduce concurrent operations'],
        longTermFix: 'Code optimization, load balancing, hardware upgrade, async processing',
        affectedComponents: ['CPU', 'Application Server'],
        probability: 10
    },

    // DATA SYNCHRONIZATION ERRORS
    {
        id: 'SYNC_001',
        category: 'data',
        name: 'Price Sync Failure',
        description: 'Failed to sync latest pricing from central system',
        severity: 'high',
        errorCode: 'PRICE_SYNC_FAILED',
        message: 'Price synchronization failed - using stale prices',
        symptoms: ['Wrong prices', 'Customer complaints', 'Price discrepancies'],
        causes: ['Network failure', 'Sync job failed', 'Data format error', 'Timeout'],
        businessImpact: 'Revenue loss from undercharging, customer disputes from overcharging, pricing errors',
        immediateActions: ['Manual price check', 'Force sync retry', 'Manager price verification'],
        longTermFix: 'Robust sync mechanism, conflict resolution, price verification alerts, rollback capability',
        affectedComponents: ['Price Database', 'Sync Service'],
        probability: 15
    },
    {
        id: 'SYNC_002',
        category: 'data',
        name: 'Inventory Sync Conflict',
        description: 'Conflicting inventory updates from multiple terminals',
        severity: 'medium',
        errorCode: 'SYNC_CONFLICT',
        message: 'Inventory sync conflict - concurrent updates detected',
        symptoms: ['Inconsistent stock levels', 'Overselling', 'Stock discrepancies'],
        causes: ['Concurrent sales', 'Network partition', 'Sync race condition'],
        businessImpact: 'Inventory accuracy issues, potential overselling, fulfillment problems',
        immediateActions: ['Resolve conflict manually', 'Physical count', 'Last write wins strategy'],
        longTermFix: 'Implement CRDT, version vectors, distributed locking, eventual consistency handling',
        affectedComponents: ['Inventory Database', 'Sync Engine'],
        probability: 12
    },

    // SYSTEM CONFIGURATION ERRORS
    {
        id: 'SYS_001',
        category: 'system',
        name: 'Configuration Mismatch',
        description: 'POS terminal configuration doesn\'t match central settings',
        severity: 'medium',
        errorCode: 'CONFIG_MISMATCH',
        message: 'Configuration mismatch detected - terminal settings incorrect',
        symptoms: ['Wrong behavior', 'Feature not working', 'Unexpected errors'],
        causes: ['Failed config update', 'Manual override', 'Version mismatch'],
        businessImpact: 'System operating incorrectly, potential compliance issues, feature unavailability',
        immediateActions: ['Force config refresh', 'Restore default config', 'Manual configuration'],
        longTermFix: 'Automated config management, version control, validation checks, rollback capability',
        affectedComponents: ['Configuration Service', 'POS Terminal'],
        probability: 10
    },
    {
        id: 'SYS_002',
        category: 'system',
        name: 'Software Version Incompatibility',
        description: 'POS client version incompatible with server',
        severity: 'critical',
        errorCode: 'VERSION_MISMATCH',
        message: 'Software version incompatible - upgrade required',
        symptoms: ['Cannot connect', 'API errors', 'Feature missing'],
        causes: ['Stale client', 'Server upgrade', 'Failed auto-update'],
        businessImpact: 'Terminal completely non-functional, cannot process any transactions',
        immediateActions: ['Update software', 'Rollback server', 'Use compatible terminal'],
        longTermFix: 'Automated updates, backward compatibility, version negotiation, staged rollouts',
        affectedComponents: ['Software Update System', 'API Gateway'],
        probability: 5
    },
    {
        id: 'SYS_003',
        category: 'system',
        name: 'Time Synchronization Error',
        description: 'System clock out of sync with time server',
        severity: 'medium',
        errorCode: 'TIME_SYNC_ERROR',
        message: 'System time out of sync - transactions may have incorrect timestamps',
        symptoms: ['Wrong transaction times', 'Certificate errors', 'Auth failures'],
        causes: ['NTP server unreachable', 'Clock drift', 'Battery failure', 'Network issue'],
        businessImpact: 'Incorrect transaction timestamps, audit issues, payment auth failures, security cert errors',
        immediateActions: ['Manual time correction', 'Sync with time server', 'Replace CMOS battery'],
        longTermFix: 'Redundant NTP servers, automatic time sync monitoring, hardware maintenance',
        affectedComponents: ['System Clock', 'NTP Client'],
        probability: 8
    },
    {
        id: 'SYS_004',
        category: 'system',
        name: 'License Expiration',
        description: 'POS software license expired or about to expire',
        severity: 'critical',
        errorCode: 'LICENSE_EXPIRED',
        message: 'Software license expired - system will stop functioning',
        symptoms: ['Warning messages', 'Feature lockout', 'System shutdown imminent'],
        causes: ['License renewal forgotten', 'Payment failed', 'License server unreachable'],
        businessImpact: 'Complete system shutdown, business operations stopped, revenue loss',
        immediateActions: ['Renew license immediately', 'Contact vendor', 'Emergency license extension'],
        longTermFix: 'License management system, renewal reminders, auto-renewal, grace period implementation',
        affectedComponents: ['License Manager', 'Application Core'],
        probability: 4
    },

    // ADDITIONAL REALISTIC SCENARIOS
    {
        id: 'MISC_001',
        category: 'integration',
        name: 'Gift Card Balance Check Failed',
        description: 'Unable to verify gift card balance with issuer',
        severity: 'high',
        errorCode: 'GIFT_CARD_ERROR',
        message: 'Gift card balance verification failed - cannot process',
        symptoms: ['Cannot validate card', 'Customer frustrated', 'Transaction blocked'],
        causes: ['Gift card server down', 'Invalid card number', 'Network timeout'],
        businessImpact: 'Cannot accept gift cards, customer dissatisfaction, lost sale',
        immediateActions: ['Try alternative terminal', 'Manual authorization', 'Accept on trust with ID'],
        longTermFix: 'Offline balance cache, backup verification system, clear escalation process',
        affectedComponents: ['Gift Card API', 'Payment Gateway'],
        probability: 12
    },
    {
        id: 'MISC_002',
        category: 'system',
        name: 'Excessive Failed Login Attempts',
        description: 'Account locked due to repeated failed login attempts',
        severity: 'medium',
        errorCode: 'ACCOUNT_LOCKED',
        message: 'Account locked - too many failed login attempts',
        symptoms: ['Cannot login', 'Security alert', 'Manager intervention needed'],
        causes: ['Forgotten password', 'Brute force attack', 'Caps lock on', 'Account sharing'],
        businessImpact: 'Terminal unavailable, reduced capacity, potential security breach',
        immediateActions: ['Admin unlock', 'Password reset', 'Security check'],
        longTermFix: 'Better password policy, MFA implementation, security training',
        affectedComponents: ['Authentication System', 'Security Module'],
        probability: 14
    },
    {
        id: 'MISC_003',
        category: 'hardware',
        name: 'Customer Display Not Working',
        description: 'Customer-facing display screen not showing transaction',
        severity: 'low',
        errorCode: 'DISPLAY_ERROR',
        message: 'Customer display malfunction - customer cannot view transaction',
        symptoms: ['Blank screen', 'Customer confusion', 'Trust issues'],
        causes: ['Cable disconnected', 'Display driver error', 'Hardware failure', 'Power issue'],
        businessImpact: 'Customer cannot verify charges, trust issues, potential disputes',
        immediateActions: ['Check cables', 'Restart display', 'Verbal price confirmation'],
        longTermFix: 'Regular hardware checks, display monitoring, backup display options',
        affectedComponents: ['Customer Display', 'Display Driver'],
        probability: 18
    },
    {
        id: 'MISC_004',
        category: 'payment',
        name: 'Contactless Payment Rejected',
        description: 'NFC/contactless payment failed to process',
        severity: 'medium',
        errorCode: 'CONTACTLESS_FAILED',
        message: 'Contactless payment declined - please insert card',
        symptoms: ['Tap not working', 'Need to insert card', 'Customer confusion'],
        causes: ['Card needs PIN', 'Amount exceeds contactless limit', 'Reader malfunction', 'Card damaged'],
        businessImpact: 'Transaction delay, customer inconvenience, switch to slower chip read',
        immediateActions: ['Insert chip instead', 'Try again', 'Clean reader'],
        longTermFix: 'Clear contactless limit signage, reader maintenance, customer education',
        affectedComponents: ['NFC Reader', 'Payment Terminal'],
        probability: 20
    },
    {
        id: 'MISC_005',
        category: 'inventory',
        name: 'Serial Number Duplicate',
        description: 'Product serial number already exists in system',
        severity: 'medium',
        errorCode: 'DUPLICATE_SERIAL',
        message: 'Serial number already registered - possible counterfeit or data error',
        symptoms: ['Cannot register product', 'Warranty issue', 'Investigation needed'],
        causes: ['Counterfeit product', 'Return restock error', 'Data entry mistake', 'System glitch'],
        businessImpact: 'Cannot complete sale, potential fraud, warranty problems, customer dissatisfaction',
        immediateActions: ['Verify product authenticity', 'Check history', 'Manager decision'],
        longTermFix: 'Serial number validation, supplier verification, anti-counterfeit measures',
        affectedComponents: ['Product Registration', 'Inventory System'],
        probability: 6
    },
    {
        id: 'MISC_006',
        category: 'system',
        name: 'Thermal Printer Overheating',
        description: 'Receipt printer overheating and shutting down',
        severity: 'medium',
        errorCode: 'PRINTER_OVERHEAT',
        message: 'Printer overheating - thermal protection activated',
        symptoms: ['Printer stops', 'Warm to touch', 'Auto shutdown'],
        causes: ['Continuous use', 'Poor ventilation', 'Hardware aging', 'High ambient temperature'],
        businessImpact: 'Cannot print receipts, customer service degraded, compliance issues',
        immediateActions: ['Let cool down', 'Improve ventilation', 'Use backup printer'],
        longTermFix: 'Better cooling, usage limits, printer rotation, hardware upgrade',
        affectedComponents: ['Thermal Printer', 'Hardware'],
        probability: 10
    },

    // 🎯 NEW SCENARIOS (ADDED)
    {
        id: 'PAY_006',
        category: 'payment',
        name: 'Digital Wallet Handshake Failure',
        description: 'Apple Pay / Google Pay NFC handshake failed',
        severity: 'medium',
        errorCode: 'WALLET_HANDSHAKE_FAIL',
        message: 'Digital wallet NFC handshake failed - device moved too quickly',
        symptoms: ['Phone vibrates but no payment', 'Terminal beeps error', 'Retry prompt'],
        causes: ['Device moved too fast', 'NFC interference', 'Case blocking signal', 'Terminal NFC reader lag'],
        businessImpact: 'Checkout delay, customer frustration, forced to use physical card',
        immediateActions: ['Retry holding device steady', 'Remove phone case', 'Use physical card'],
        longTermFix: 'Adjust NFC reader sensitivity, update terminal firmware, improve user guidance on screen',
        affectedComponents: ['NFC Reader', 'Payment Terminal'],
        probability: 20
    },
    {
        id: 'PAY_007',
        category: 'payment',
        name: 'Currency Conversion Error',
        description: 'Dynamic Currency Conversion (DCC) service unavailable',
        severity: 'low',
        errorCode: 'DCC_SERVICE_UNAVAILABLE',
        message: 'Currency conversion service unavailable - processing in local currency only',
        symptoms: ['No currency choice offered', 'Processed in local currency', 'Customer asks for home currency'],
        causes: ['DCC provider API down', 'Rate table expired', 'Network timeout'],
        businessImpact: 'Lost forex revenue share, international customer inconvenience',
        immediateActions: ['Process in local currency', 'Inform customer', 'Manual rate calculation (not recommended)'],
        longTermFix: 'Cache exchange rates locally, redundant DCC providers, offline fallback mode',
        affectedComponents: ['Payment Gateway', 'DCC Service'],
        probability: 8
    },
    {
        id: 'INV_005',
        category: 'inventory',
        name: 'Damaged Item Return Error',
        description: 'System rejecting return of damaged item due to condition code',
        severity: 'medium',
        errorCode: 'RETURN_CONDITION_REJECT',
        message: 'Return rejected - condition code "DAMAGED" requires manager override',
        symptoms: ['Return blocked', 'Manager approval prompt', 'Customer waiting'],
        causes: ['Strict return policy config', 'Wrong condition code selected', 'User error'],
        businessImpact: 'Customer service friction, line buildup, potential conflict',
        immediateActions: ['Manager override', 'Change condition code (if appropriate)', 'Manual refund'],
        longTermFix: 'Review return policy rules, staff training on condition codes, improved UI for returns',
        affectedComponents: ['Returns Management', 'Inventory System'],
        probability: 12
    },
    {
        id: 'INV_006',
        category: 'inventory',
        name: 'Bundle SKU Decomposition Fail',
        description: 'Selling a bundle failed to deduct individual component stock',
        severity: 'high',
        errorCode: 'BUNDLE_DECOMP_FAIL',
        message: 'Bundle sale recorded but component inventory not updated',
        symptoms: ['Stock mismatch', 'Components show available when sold', 'Fulfillment error'],
        causes: ['Database trigger failure', 'Missing component mapping', 'Sync delay'],
        businessImpact: 'Inventory inaccuracy, potential overselling of components, audit failure',
        immediateActions: ['Manual inventory adjustment', 'Audit bundle sales', 'Stop bundle sales'],
        longTermFix: 'Transactional bundle logic, nightly reconciliation job, strict mapping validation',
        affectedComponents: ['Inventory Database', 'Product Catalog'],
        probability: 6
    },
    {
        id: 'NET_004',
        category: 'network',
        name: 'DNS Resolution Failure',
        description: 'POS terminal cannot resolve payment gateway hostname',
        severity: 'critical',
        errorCode: 'DNS_RESOLUTION_FAIL',
        message: 'DNS lookup failed for payment gateway - check network settings',
        symptoms: ['Payment failed', 'Internet working but specific services down', 'Error code DNS_NXDOMAIN'],
        causes: ['DNS server outage', 'Misconfigured DNS IP', 'ISP issue', 'Local cache poisoning'],
        businessImpact: 'Cannot process payments, system offline behavior, major operational disruption',
        immediateActions: ['Switch to backup DNS (8.8.8.8)', 'Flush DNS cache', 'Restart router'],
        longTermFix: 'Hardcoded backup IP (risky), local DNS caching forwarder, redundant ISP connections',
        affectedComponents: ['Network Stack', 'DNS Resolver'],
        probability: 5
    },
    {
        id: 'NET_005',
        category: 'network',
        name: 'SSL Certificate Expired',
        description: 'Connection to backend API failed due to expired SSL cert',
        severity: 'critical',
        errorCode: 'SSL_CERT_EXPIRED',
        message: 'SSL Handshake failed - server certificate expired',
        symptoms: ['Secure connection failed', 'Red lock icon', 'API calls failing'],
        causes: ['Certificate renewal missed', 'Wrong cert installed', 'Clock skew on terminal'],
        businessImpact: 'Total loss of connectivity to secure services, compliance violation, system downtime',
        immediateActions: ['Emergency cert renewal', 'Bypass SSL (dev only - dangerous)', 'Correct system time'],
        longTermFix: 'Automated cert management (LetsEncrypt), monitoring alerts 30 days prior, pinned certs update mechanism',
        affectedComponents: ['Security Layer', 'Network Client'],
        probability: 3
    },
    {
        id: 'HW_005',
        category: 'hardware',
        name: 'Scale Calibration Error',
        description: 'Integrated weighing scale reporting unstable or negative weight',
        severity: 'high',
        errorCode: 'SCALE_CALIBRATION_ERR',
        message: 'Scale unstable or uncalibrated - cannot weigh item',
        symptoms: ['Weight fluctuates', 'Cannot add weighed item', 'Zero error'],
        causes: ['Debris under platter', 'Hardware drift', 'Vibration', 'Sensor failure'],
        businessImpact: 'Cannot sell produce/bulk items, revenue loss, legal weights & measures violation',
        immediateActions: ['Clean scale', 'Zero/Tare scale', 'Manual weight entry', 'Close lane'],
        longTermFix: 'Regular professional calibration, vibration dampening mounts, daily zero check enforcement',
        affectedComponents: ['Weighing Scale', 'POS Interface'],
        probability: 15
    },
    {
        id: 'HW_006',
        category: 'hardware',
        name: 'Biometric Reader Failure',
        description: 'Fingerprint reader for manager override not responding',
        severity: 'medium',
        errorCode: 'BIOMETRIC_READ_FAIL',
        message: 'Fingerprint reader timeout - use password fallback',
        symptoms: ['Manager cannot approve', 'Login failed', 'Device not found'],
        causes: ['Dirty sensor', 'Wet finger', 'Driver crash', 'USB disconnect'],
        businessImpact: 'Slow approvals, manager frustration, security bypass temptation',
        immediateActions: ['Use password', 'Clean sensor', 'Replug device'],
        longTermFix: 'High-quality sensors, multi-modal auth (PIN + Card), regular cleaning protocol',
        affectedComponents: ['Biometric Scanner', 'Auth System'],
        probability: 10
    },
    {
        id: 'SEC_004',
        category: 'security',
        name: 'Session Token Expired',
        description: 'User session expired mid-transaction',
        severity: 'medium',
        errorCode: 'SESSION_EXPIRED',
        message: 'Session expired - please log in again to continue',
        symptoms: ['Logged out suddenly', 'Save failed', 'Auth prompt'],
        causes: ['Long inactivity', 'Token timeout policy', 'Clock skew', 'Server restart'],
        businessImpact: 'Transaction interrupted, data loss if not auto-saved, staff annoyance',
        immediateActions: ['Re-login', 'Restore cart from local storage'],
        longTermFix: 'Refresh token rotation, auto-save cart state, extend session on activity',
        affectedComponents: ['Auth Service', 'Session Manager'],
        probability: 25
    },
    {
        id: 'SEC_005',
        category: 'security',
        name: 'Unauthorized Refund Attempt',
        description: 'Cashier attempted refund above authorized limit',
        severity: 'high',
        errorCode: 'AUTH_LIMIT_EXCEEDED',
        message: 'Refund amount exceeds user limit - manager approval required',
        symptoms: ['Action blocked', 'Manager prompt', 'Security log entry'],
        causes: ['Policy enforcement', 'User error', 'Potential theft attempt'],
        businessImpact: 'Process delay, security flag, potential internal fraud prevention',
        immediateActions: ['Manager approval', 'Reduce amount', 'Cancel transaction'],
        longTermFix: 'Role-based limits review, real-time fraud scoring, dual-custody for high value refunds',
        affectedComponents: ['Access Control', 'Transaction Logic'],
        probability: 15
    },
    {
        id: 'DATA_001',
        category: 'data',
        name: 'Customer Profile Corrupt',
        description: 'Cannot load customer loyalty profile due to JSON error',
        severity: 'medium',
        errorCode: 'PROFILE_LOAD_ERROR',
        message: 'Failed to load customer profile - data format invalid',
        symptoms: ['Customer lookup fails', 'Loyalty points unavailable', 'Error popup'],
        causes: ['Bad migration', 'Encoding issue', 'Truncated data', 'API schema change'],
        businessImpact: 'Poor customer experience, cannot accrue points, personalized offers unavailable',
        immediateActions: ['Skip loyalty', 'Create new temp profile', 'Lookup by phone instead of card'],
        longTermFix: 'Data validation on write, schema versioning, automated data repair tools',
        affectedComponents: ['Customer Database', 'CRM API'],
        probability: 5
    },
    {
        id: 'DATA_002',
        category: 'data',
        name: 'Tax Rate Table Missing',
        description: 'Local tax rate table for current region not found',
        severity: 'critical',
        errorCode: 'TAX_TABLE_MISSING',
        message: 'Critical: Tax rates not loaded for store region',
        symptoms: ['Cannot calculate tax', 'Transaction blocked', 'Compliance warning'],
        causes: ['Sync failure', 'Config error', 'File corruption', 'New store setup incomplete'],
        businessImpact: 'Illegal to sell without tax, store shutdown risk, compliance fines',
        immediateActions: ['Manual tax entry (emergency)', 'Force config sync', 'Load default flat rate'],
        longTermFix: 'Hardcoded fallback rates, cloud config backup, startup validation check',
        affectedComponents: ['Tax Engine', 'Configuration'],
        probability: 2
    },
    {
        id: 'SYS_005',
        category: 'system',
        name: 'Peripheral Driver Crash',
        description: 'Universal peripheral driver service stopped unexpectedly',
        severity: 'high',
        errorCode: 'DRIVER_SERVICE_STOPPED',
        message: 'Peripheral service stopped - scanner and printer unavailable',
        symptoms: ['All devices dead', 'Windows/Linux service alert', 'Restart required'],
        causes: ['Memory leak', 'Driver conflict', 'OS update', 'Hardware surge'],
        businessImpact: 'Terminal unusable, reboot takes 5 mins, customer queue buildup',
        immediateActions: ['Restart service', 'Reboot terminal', 'Move customer'],
        longTermFix: 'Driver stability updates, service auto-restart watchdog, OS compatibility testing',
        affectedComponents: ['OS Services', 'Hardware Drivers'],
        probability: 8
    },
    {
        id: 'SYS_006',
        category: 'system',
        name: 'Disk Write Permission Denied',
        description: 'Application cannot write to local log or temp directory',
        severity: 'high',
        errorCode: 'DISK_WRITE_DENIED',
        message: 'FileSystem Error: Access denied writing to /var/log/pos',
        symptoms: ['Logs missing', 'App crash on save', 'Error popup'],
        causes: ['Permissions change', 'Antivirus lock', 'User account issue', 'Read-only mount'],
        businessImpact: 'Data loss risk, application instability, lack of audit trail',
        immediateActions: ['Run as admin', 'Fix permissions', 'Disable antivirus temp'],
        longTermFix: 'Correct folder permission setup script, run as service account, monitor disk health',
        affectedComponents: ['File System', 'OS Security'],
        probability: 6
    },
    {
        id: 'INT_004',
        category: 'integration',
        name: 'Kitchen Display System (KDS) Timeout',
        description: 'Order failed to send to kitchen display controller',
        severity: 'high',
        errorCode: 'KDS_TIMEOUT',
        message: 'Kitchen order not sent - KDS controller unreachable',
        symptoms: ['Kitchen unaware of order', 'Food not prepared', 'Server error'],
        causes: ['Network partition', 'KDS crash', 'Queue full', 'Firewall'],
        businessImpact: 'Lost orders, angry customers, food waste, chaotic kitchen operations',
        immediateActions: ['Print kitchen ticket (backup)', 'Walk order to kitchen', 'Restart KDS'],
        longTermFix: 'Local print fallback, KDS redundancy, persistent message queue',
        affectedComponents: ['KDS Interface', 'Network'],
        probability: 10
    },
    {
        id: 'INT_005',
        category: 'integration',
        name: 'Accounting Sync Failure',
        description: 'End-of-day sales data failed to post to ERP/Accounting',
        severity: 'medium',
        errorCode: 'ERP_SYNC_FAIL',
        message: 'EOD Sync Error: Could not post batch to SAP/Oracle',
        symptoms: ['Reconciliation mismatch', 'Finance team alert', 'Missing revenue data'],
        causes: ['ERP downtime', 'Schema mismatch', 'Auth failure', 'Data validation error'],
        businessImpact: 'Financial reporting delay, manual reconciliation effort, audit risk',
        immediateActions: ['Retry batch', 'Export CSV', 'Manual entry'],
        longTermFix: 'Async queue with retry, dead letter queue, detailed validation logs',
        affectedComponents: ['Accounting Bridge', 'ERP Connector'],
        probability: 15
    },
    {
        id: 'PERF_004',
        category: 'performance',
        name: 'UI Thread Blocked',
        description: 'Main UI thread frozen by heavy calculation',
        severity: 'medium',
        errorCode: 'UI_FREEZE',
        message: 'Application not responding - processing large dataset',
        symptoms: ['Screen frozen', 'Spinner stuck', 'OS "Wait/Close" prompt'],
        causes: ['Large product list load', 'Complex report generation', 'Sync on main thread'],
        businessImpact: 'Staff frustration, perceived slowness, potential force quit and data loss',
        immediateActions: ['Wait it out', 'Force quit'],
        longTermFix: 'Move heavy work to WebWorkers/Background threads, virtualize lists, pagination',
        affectedComponents: ['UI Layer', 'Rendering Engine'],
        probability: 20
    },
    {
        id: 'PERF_005',
        category: 'performance',
        name: 'Database Index Missing',
        description: 'Product search extremely slow due to full table scan',
        severity: 'medium',
        errorCode: 'SLOW_QUERY_DETECTED',
        message: 'Product search timeout - query took > 5000ms',
        symptoms: ['Search lag', 'Spinner', 'Database CPU spike'],
        causes: ['Index dropped', 'Bad query plan', 'Data volume growth'],
        businessImpact: 'Slow service, customer wait time, battery drain on mobile POS',
        immediateActions: ['Restart DB', 'Clear cache'],
        longTermFix: 'Add missing indexes, query optimization, search engine (Elasticsearch) integration',
        affectedComponents: ['Database', 'Search Engine'],
        probability: 8
    },
    {
        id: 'MISC_007',
        category: 'system',
        name: 'Font Rendering Error',
        description: 'Receipt font corrupted or missing characters',
        severity: 'low',
        errorCode: 'FONT_RENDER_FAIL',
        message: 'Receipt print error - invalid character set',
        symptoms: ['Garbage text on receipt', 'Boxes instead of text', 'Wrong language'],
        causes: ['Codepage mismatch', 'Font file missing', 'Driver bug'],
        businessImpact: 'Unreadable receipts, professional image damage, legal compliance (tax ID readable?)',
        immediateActions: ['Reprint', 'Restart printer', 'Use image mode'],
        longTermFix: 'Embed fonts in printer, use standard codepages, PDF receipt generation',
        affectedComponents: ['Printer Driver', 'Rendering'],
        probability: 5
    },
    {
        id: 'MISC_008',
        category: 'security',
        name: 'USB Port Security Violation',
        description: 'Unauthorized USB device detected on terminal',
        severity: 'high',
        errorCode: 'USB_SECURITY_ALERT',
        message: 'Security Alert: Unauthorized USB mass storage device detected',
        symptoms: ['Security popup', 'Port disabled', 'Admin alert'],
        causes: ['Staff charging phone', 'Malicious drive', 'Keylogger attempt'],
        businessImpact: 'Potential data exfiltration, malware infection, PCI violation',
        immediateActions: ['Remove device', 'Scan terminal', 'Report incident'],
        longTermFix: 'Physical port locks, OS-level USB allowlisting, endpoint protection software',
        affectedComponents: ['OS Security', 'Hardware Ports'],
        probability: 8
    }
];

/**
 * Get random error scenario based on probability distribution
 */
export function getRandomError(): POSErrorScenario {
    const totalProbability = POS_ERROR_SCENARIOS.reduce((sum, scenario) => sum + scenario.probability, 0);
    let random = Math.random() * totalProbability;

    for (const scenario of POS_ERROR_SCENARIOS) {
        random -= scenario.probability;
        if (random <= 0) {
            return scenario;
        }
    }

    return POS_ERROR_SCENARIOS[0]; // Fallback
}

/**
 * Get error by ID
 */
export function getErrorById(id: string): POSErrorScenario | undefined {
    return POS_ERROR_SCENARIOS.find(scenario => scenario.id === id);
}

/**
 * Get errors by category
 */
export function getErrorsByCategory(category: POSErrorScenario['category']): POSErrorScenario[] {
    return POS_ERROR_SCENARIOS.filter(scenario => scenario.category === category);
}

/**
 * Get errors by severity
 */
export function getErrorsBySeverity(severity: POSErrorScenario['severity']): POSErrorScenario[] {
    return POS_ERROR_SCENARIOS.filter(scenario => scenario.severity === severity);
}
