packages:
  # Main demo POS application
  - 'demo-pos-app'
  
  # Standalone StackLens monorepo
  - 'stacklens/**'
  
  # POS Demo monorepo  
  - 'pos-demo/**'
  
  # Shared packages
  - 'packages/**'
